spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false
    username: ${DB_USERNAME:aaa}
    password: ${DB_PASSWORD:bbb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 240000
      maximum-pool-size: 8
      minimum-idle: 3
      validation-timeout: 3000
      leak-detection-threshold: 60000
      validation-query: SELECT 1
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1
      auto-commit: true

server:
  servlet:
    context-path: /app-test
  port: 8888

# milvus 相关配置
milvus:
  host: http://192.168.0.251
  port: 19530
  token: blue:Blue19_TEST
  client-key: client
  pool:
    max-idle-per-key: 20
    max-total-per-key: 50
    max-total: 100
    wait-duration: 60
    evictable-duration: 120
